name: Release

on: [push]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Scala caches
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-docs-${{ hashFiles('**/*.sbt') }}
    - uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: temurin
    - uses: olafurpg/setup-gpg@v3
      if: startsWith(github.ref, 'refs/tags/v')
    - name: "Publish release: ${{github.ref}}"
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        echo GITHUB_REF=$GITHUB_REF
        export PUBLISH_ONLY=$(echo $GITHUB_REF | grep -P "refs/tags/(\K[^/]*)" -o)
        echo PUBLISH_ONLY=$PUBLISH_ONLY
        RELEASE=1 sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    - name: "Publish snapshot: ${{github.ref}}"
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
